obj-$(CONFIG_MCU) += mcu.o

mcu-$(CONFIG_MCU_LDISC) += mcu_ldisc.o
mcu-$(CONFIG_MCU_CORE) += mcu_core.o
mcu-$(CONFIG_MCU_GPIO) += mcu_gpio.o
mcu-$(CONFIG_MCU_OLED) += mcu_oled.o
mcu-$(CONFIG_MCU_BATTERY) += mcu_battery.o

