obj-$(CONFIG_MCU) += mcu.o

mcu-y += mcu-packet.o
mcu-$(CONFIG_MCU_LDISC) += mcu-ldisc.o
mcu-$(CONFIG_MCU_CORE) += mcu-core.o
mcu-$(CONFIG_MCU_GPIO) += mcu-gpio.o
mcu-$(CONFIG_MCU_OLED) += mcu-oled.o
mcu-$(CONFIG_MCU_BATTERY) += mcu-battery.o

